-- AlterTable
ALTER TABLE "device_code" ADD COLUMN     "pollingInterval" INTEGER,
ADD COLUMN     "status" TEXT,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
